### ISSUE TITLE
Add GitHub links to DESCRIPTION?

### ISSUE THREAD

**Issue by maelle** [lvaudor/recitR#2]
Via `usethis::use_github_links()` for instance. This way pkgdown will add links to the GitHub repo from the pkgdown website. :slightly_smiling_face:

**Comment by lvaudor** [comment]
Yes, it's done. Thanks for the tip!

**Comment by maelle** [comment]
And I forgot my other favourite tip, you can add the link to the pkgdown website in the description of the GitHub repository (top right of the GitHub repo landing page). :-)
